// Code generated by goctl. DO NOT EDIT.
package types

type CancelOrderRequest struct {
	Address string `json:"address"`
	OrderId string `json:"orderId"`
}

type AllOrdersRequest struct {
	Address   string `json:"address"`
	Symbol    string `json:"symbol"`
	StartIime uint64 `json:"startIime"`
	EndIime   uint64 `json:"endIime"`
	Limit     uint64 `json:"limit"`
}

type CommResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type OrderRequest struct {
	Uid           string `json:"uid"`
	Symbol        string `json:"symbol"`
	Price         string `json:"price, optional"`
	Quantity      string `json:"quantity, optional"`
	QuoteOrderQty string `json:"quoteOrderQty, optional"`
	Side          string `json:"side"`
	Type          string `json:"type"`
}

type OrderResponse struct {
	CommResp
	Symbol      string `json:"symbol"`
	OrderId     string `json:"orderId"`
	Price       string `json:"price"`
	OrigQty     string `json:"origQty"`
	ExecutedQty string `json:"executedQty"`
	Type        string `json:"type"`
	Side        string `json:"side"`
	Status      string `json:"status"`
}
