// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/enterSpace9527/hifive-trade/trade/trade_service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/order",
				Handler: orderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/cancelOrder",
				Handler: cancelOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/getOrder",
				Handler: getOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/allOrders",
				Handler: allOrdersHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/test",
				Handler: testHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/update",
				Handler: updateHandler(serverCtx),
			},
		},
	)
}
